### ISSUE TITLE
Issue with installed app from Play Store

### ISSUE THREAD

**Issue by AzimLord** [msarhan/ummalqura-calendar#17]
Salam guys,
Im getting this error when I install my app from the Play Store

`Caused by java.util.MissingResourceException: Can't find bundle for base name com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData, locale en
       at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)
       at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1381)
       at java.util.ResourceBundle.getBundle(ResourceBundle.java:847)
       at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.getMonths(Unknown Source:38)
       at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.(Unknown Source:10)
       at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(Unknown Source:5)`

Can someone help me with this issue?

**Comment by AhmedAmeenEbdaa** [comment]
@AzimLord Could you please mention your device name and Android version because I'm facing the same issue?

**Comment by joeyoggie** [comment]
I'm also having the same bug on Huwawi P30 Pro (Android 10), with Arabic locale.

**Comment by devshot-dotcom** [comment]
The issue persists. I built an app last year and it had the same issue, the debug version would work perfectly while the release won't. The issue is still the same.

**Comment by nirobhasanbd** [comment]
@msarhan Could you please take step about this issue. I also facing the same issue for release version in google play. In my case device is Nexus 5x, OS Android 6.0.1
Stack trace:

`Fatal Exception: java.util.MissingResourceException: Can't find resource for bundle 'com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_en', key ''
       at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
       at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
       at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
       at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.initializeData(UmmalquraDateFormatSymbols.java)
       at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.<init>(UmmalquraDateFormatSymbols.java)
       at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(UmmalquraCalendar.java)
       at com.infinity.quran.mvvm.prayer.view.PrayerActivity.getHijriDateStr(PrayerActivity.java)
       at com.infinity.quran.mvvm.prayer.view.PrayerActivity.onCreateView(PrayerActivity.java)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Crashlytics console image:
![Screen Shot 2021-08-29 at 12 18 24 PM](https://user-images.githubusercontent.com/62602617/131240785-9c3d9856-747c-434f-9f60-ee458948a9ef.png)

**Comment by nirobhasanbd** [comment]
@msarhan issue solved:
This issue is happening for `minifyEnabled true`
Usually minifyEnabled is set to true for release build only so this issue was generate only in release build.

So the solution is:
Insert the below line to you proguard-rules.pro file
-keep public class com.github.msarhan.** { *; }

Thanks.
