### ISSUE TITLE
Using library in Android API 22 throws StackoverflowException

### ISSUE THREAD

**Issue by anagri** [msarhan/ummalqura-calendar#3]
java.lang.StackOverflowError
            at java.util.Arrays.binarySearch(Arrays.java:411)
            at java.util.Arrays.binarySearch(Arrays.java:391)
            at libcore.util.ZoneInfo.getOffset(ZoneInfo.java:207)
            at libcore.util.ZoneInfo.getOffset(ZoneInfo.java:201)
            at java.util.GregorianCalendar.fullFieldsCalc(GregorianCalendar.java:493)
            at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:573)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:311)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calendar.getTimeInMillis(Calendar.java:1034)
            at java.util.Calendar.getTime(Calendar.java:1021)
            at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:317)
            at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:783)
            at java.util.Calen

**Comment by msarhan** [comment]
I've made a fix to this,
If still exists, please to send a code snippet to regenerate the error.
